import './globals.css'
import { Inter } from 'next/font/google'
import NavBar from './NavBar'

const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <div className='bg-white w-screen h-screen bg-gradient-to-bl from-slate-700 to-slate-900 text-white'>
          <NavBar />
          {children}
        </div>
      </body>
    </html>
  )
}
